import { createFileRoute, Link } from "@tanstack/react-router";
import { useEffect, useState } from "react";
import { ArrowLeft, BarChart3, Building2, Megaphone, Package, Plus, Send } from "lucide-react";
import { toast } from "sonner";
import { Button } from "@/components/ui/button";
import { StoreEditor } from "@/components/StoreEditor";
import { StoreStats } from "@/components/StoreStats";
import { PartnerPlanCard } from "@/components/PartnerPlanCard";
import { createCampaign, createProduct, createStore, listCampaignResults, listMyStores, listStoreCampaigns, listStoreProducts, setProductPublished, submitCampaign, uploadStoreAsset, type Campaign, type Product, type Store } from "@/lib/commerce";

export const Route = createFileRoute("/app/store-portal")({
  head: () => ({ meta: [{ title: "Portal das lojas — Stylisme" }, { name: "description", content: "Cadastre sua loja, produtos e campanhas patrocinadas no Stylisme." }, { property: "og:title", content: "Portal das lojas — Stylisme" }, { property: "og:description", content: "Gerencie produtos, campanhas e resultados medidos." }, { property: "og:type", content: "website" }, { name: "twitter:card", content: "summary" }] }), component: StorePortal,
});

type Tab = "overview" | "product" | "campaign";
function StorePortal() {
  const [stores, setStores] = useState<Store[]>([]); const [selected, setSelected] = useState<string>("");
  const [products, setProducts] = useState<Product[]>([]); const [campaigns, setCampaigns] = useState<Campaign[]>([]); const [tab, setTab] = useState<Tab>("overview");
  const [storeForm, setStoreForm] = useState({ name: "", slug: "", description: "", website: "", instagram: "", city: "" });
  const [product, setProduct] = useState({ name: "", category: "", description: "", price: "", destination: "" });
  const [campaign, setCampaign] = useState({ name: "", headline: "", cta: "Ver produto", destination: "", targetCity: "", starts: "", ends: "" });
  const [productImage, setProductImage] = useState<File | null>(null); const [campaignImage, setCampaignImage] = useState<File | null>(null);
  const [events, setEvents] = useState<{ campaign_id: string; kind: string }[]>([]);
  const load = async () => { const rows = await listMyStores(); setStores(rows); setSelected((current) => current || rows[0]?.id || ""); };
  useEffect(() => { void load().catch((e) => toast.error(e.message)); }, []);
  useEffect(() => { if (!selected) return; void Promise.all([listStoreProducts(selected), listStoreCampaigns(selected)]).then(async ([p,c]) => { setProducts(p); setCampaigns(c); setEvents(await listCampaignResults(c.map((x)=>x.id))); }).catch((e) => toast.error(e.message)); }, [selected]);
  const current = stores.find((s) => s.id === selected);
  async function addStore() { try { await createStore(storeForm); toast.success("Loja enviada para verificação."); setStoreForm({ name:"",slug:"",description:"",website:"",instagram:"",city:"" }); await load(); } catch(e) { toast.error(e instanceof Error ? e.message : "Não foi possível cadastrar."); } }
  async function addProduct() { if (!selected) return; try { const image_path=productImage?await uploadStoreAsset(selected,productImage,"product"):null; await createProduct({ store_id:selected, name:product.name, category:product.category || "geral", description:product.description, image_path, price_cents: product.price ? Math.round(Number(product.price.replace(",","."))*100) : null, destination_url:product.destination || null, published:false }); toast.success("Produto salvo como rascunho."); setProductImage(null); setProducts(await listStoreProducts(selected)); } catch(e) { toast.error(e instanceof Error ? e.message : "Não foi possível salvar."); } }
  async function addCampaign() { if (!selected) return; try { const image_path=campaignImage?await uploadStoreAsset(selected,campaignImage,"campaign"):null; await createCampaign({ store_id:selected, name:campaign.name, headline:campaign.headline, cta:campaign.cta, destination_url:campaign.destination, image_path, targeting:{scope:campaign.targetCity?"city":"national",cities:campaign.targetCity.split(",").map(c=>c.trim()).filter(Boolean)}, starts_at:campaign.starts || null, ends_at:campaign.ends || null, status:"draft" }).then((c)=>submitCampaign(c.id)); toast.success("Campanha enviada para análise do Stylisme."); setCampaignImage(null); setCampaigns(await listStoreCampaigns(selected)); } catch(e) { toast.error(e instanceof Error ? e.message : "Não foi possível salvar."); } }
  return <div className="px-5 pt-8 pb-12"><Link to="/app/profile" className="inline-flex items-center gap-2 text-xs text-muted-foreground"><ArrowLeft size={14}/> Perfil</Link><div className="mt-4 flex items-center gap-3"><Building2 className="text-gold"/><div><p className="text-[10px] uppercase tracking-[0.22em] text-muted-foreground">Parceiros</p><h1 className="font-display text-3xl">Portal das lojas</h1></div></div>
    {stores.length === 0 ? <section className="mt-6 space-y-3 border-t border-border pt-5"><h2 className="font-display text-2xl">Cadastrar loja e responsável</h2><Field label="Nome" value={storeForm.name} set={(v)=>setStoreForm({...storeForm,name:v})}/><Field label="Endereço curto" value={storeForm.slug} set={(v)=>setStoreForm({...storeForm,slug:v.toLowerCase().replace(/[^a-z0-9-]/g,"")})}/><Field label="Descrição" value={storeForm.description} set={(v)=>setStoreForm({...storeForm,description:v})}/><Field label="Site HTTPS" value={storeForm.website} set={(v)=>setStoreForm({...storeForm,website:v})}/><Field label="Instagram HTTPS" value={storeForm.instagram} set={(v)=>setStoreForm({...storeForm,instagram:v})}/><Field label="Cidade atendida (vazio = nacional)" value={storeForm.city} set={(v)=>setStoreForm({...storeForm,city:v})}/><Button className="w-full" onClick={()=>void addStore()}><Plus/> Enviar para verificação</Button></section> : <>
      <select value={selected} onChange={(e)=>setSelected(e.target.value)} className="mt-6 w-full rounded-xl border border-border bg-card px-4 py-3">{stores.map((s)=><option key={s.id} value={s.id}>{s.name}</option>)}</select>
      {current && <p className="mt-2 text-xs text-muted-foreground">Situação: <b>{current.status}</b>{current.rejection_reason ? ` · ${current.rejection_reason}` : ""}</p>}
      <div className="mt-5 grid grid-cols-3 gap-2"><TabButton icon={BarChart3} active={tab==="overview"} onClick={()=>setTab("overview")}>Resumo</TabButton><TabButton icon={Package} active={tab==="product"} onClick={()=>setTab("product")}>Produtos</TabButton><TabButton icon={Megaphone} active={tab==="campaign"} onClick={()=>setTab("campaign")}>Campanhas</TabButton></div>
      {tab==="overview" && current && <><section className="mt-6 grid grid-cols-3 gap-3"><Metric label="Produtos" value={products.length}/><Metric label="Campanhas" value={campaigns.length}/><Metric label="Ativas" value={campaigns.filter(c=>c.status==="active").length}/></section><StoreEditor store={current} onSaved={load}/><PartnerPlanCard store={current}/><StoreStats store={current} products={products} campaigns={campaigns}/></>}
      {tab==="product" && <section className="mt-6 space-y-3"><h2 className="font-display text-2xl">Novo produto</h2><Field label="Nome" value={product.name} set={(v)=>setProduct({...product,name:v})}/><Field label="Categoria" value={product.category} set={(v)=>setProduct({...product,category:v})}/><Field label="Descrição" value={product.description} set={(v)=>setProduct({...product,description:v})}/><Field label="Preço opcional" value={product.price} set={(v)=>setProduct({...product,price:v})}/><Field label="Destino HTTPS" value={product.destination} set={(v)=>setProduct({...product,destination:v})}/><FileField label="Imagem do produto" set={setProductImage}/><Button className="w-full" onClick={()=>void addProduct()}><Plus/> Salvar rascunho</Button>{products.map(p=><div key={p.id} className="flex items-center justify-between gap-3 border-t border-border py-3"><div className="min-w-0"><p className="truncate text-sm">{p.name}</p><p className="text-xs text-muted-foreground">{p.published?(current?.status==="verified"?"Publicado · visível na página da loja":"Publicado · aparece quando a loja for aprovada"):"Rascunho · só a equipe vê"}</p></div><Button size="sm" variant={p.published?"outline":"default"} onClick={()=>void setProductPublished(p.id,!p.published).then(async()=>{toast.success(p.published?"Produto voltou para rascunho.":"Produto publicado.");setProducts(await listStoreProducts(selected));}).catch((e)=>toast.error(e instanceof Error?e.message:"Não foi possível alterar."))}>{p.published?"Despublicar":"Publicar"}</Button></div>)}</section>}
      {tab==="campaign" && <section className="mt-6 space-y-3"><h2 className="font-display text-2xl">Nova campanha</h2><Field label="Nome interno" value={campaign.name} set={(v)=>setCampaign({...campaign,name:v})}/><Field label="Chamada" value={campaign.headline} set={(v)=>setCampaign({...campaign,headline:v})}/><select value={campaign.cta} onChange={(e)=>setCampaign({...campaign,cta:e.target.value})} className="w-full rounded-xl border border-border bg-card px-4 py-3"><option>Ver produto</option><option>Explorar peças</option><option>Visitar Instagram</option></select><Field label="Destino HTTPS" value={campaign.destination} set={(v)=>setCampaign({...campaign,destination:v})}/><FileField label="Imagem da campanha" set={setCampaignImage}/><Field label="Cidades (separadas por vírgula; vazio = Brasil todo)" value={campaign.targetCity} set={(v)=>setCampaign({...campaign,targetCity:v})}/><Field label="Início" type="datetime-local" value={campaign.starts} set={(v)=>setCampaign({...campaign,starts:v})}/><Field label="Fim" type="datetime-local" value={campaign.ends} set={(v)=>setCampaign({...campaign,ends:v})}/><Button className="w-full" onClick={()=>void addCampaign()}><Send/> Enviar campanha para análise</Button>{campaigns.map(c=><div key={c.id} className="border-t border-border py-3"><p className="text-sm font-medium">{c.name}</p><p className="text-xs text-muted-foreground">{c.status}{c.rejection_reason?` · ${c.rejection_reason}`:""}</p>{["draft","rejected","paused"].includes(c.status)&&<Button size="sm" variant="outline" className="mt-2" onClick={()=>void submitCampaign(c.id).then(async()=>{toast.success("Campanha enviada para análise."); if(selected) setCampaigns(await listStoreCampaigns(selected));}).catch((e)=>toast.error(e instanceof Error?e.message:"Não foi possível enviar."))}><Send/> Enviar para análise</Button>}</div>)}</section>}
    </>}
  </div>;
}
function Field({label,value,set,type="text"}:{label:string;value:string;set:(v:string)=>void;type?:string}) { return <label className="block text-[10px] uppercase text-muted-foreground">{label}<input type={type} value={value} onChange={(e)=>set(e.target.value)} className="mt-1 w-full rounded-xl border border-border bg-card px-4 py-3 text-sm normal-case text-foreground"/></label>; }
function FileField({label,set}:{label:string;set:(file:File|null)=>void}) { return <label className="block text-[10px] uppercase text-muted-foreground">{label}<input type="file" accept="image/*" onChange={(e)=>set(e.target.files?.[0]??null)} className="mt-1 w-full rounded-xl border border-border bg-card px-4 py-3 text-sm normal-case"/></label>; }
function TabButton({icon:Icon,active,onClick,children}:{icon:React.ElementType;active:boolean;onClick:()=>void;children:React.ReactNode}) { return <Button variant={active?"default":"outline"} onClick={onClick} className="h-auto flex-col py-3 text-xs"><Icon/>{children}</Button>; }
function Metric({label,value}:{label:string;value:number}) { return <div className="rounded-xl bg-card p-3 shadow-soft"><p className="font-display text-2xl">{value}</p><p className="text-[9px] uppercase text-muted-foreground">{label}</p></div>; }
function Rows({rows}:{rows:{title:string;sub:string}[]}) { return <div>{rows.map((r,i)=><div key={i} className="border-t border-border py-3"><p className="text-sm">{r.title}</p><p className="text-xs text-muted-foreground">{r.sub}</p></div>)}</div>; }
