import { createFileRoute, Link } from "@tanstack/react-router";
import { ArrowRight, Check, Crown } from "lucide-react";
import { Logo } from "@/components/Logo";
import { PLAN_RULES } from "@/lib/plan-limits";

export const Route = createFileRoute("/premium")({
  head: () => ({ meta: [{ title: "Planos Free e Premium — Stylisme" }, { name: "description", content: "Compare os planos do Stylisme. Premium por R$ 24,90 ao mês, com IA ilimitada, calendário, estatísticas e sem anúncios." }, { property: "og:title", content: "Stylisme Premium — R$ 24,90 por mês" }, { property: "og:description", content: "IA ilimitada, calendário de looks, estatísticas, provador no corpo, sincronização e sem anúncios." }, { property: "og:type", content: "website" }, { name: "twitter:card", content: "summary" }] }),
  component: PublicPremium,
});

const free = PLAN_RULES.free;
const premium = PLAN_RULES.premium;
function PublicPremium() { return <main className="min-h-screen bg-background px-5 py-6"><div className="mx-auto max-w-4xl"><nav className="flex items-center justify-between"><Link to="/" className="flex items-center gap-2"><Logo size={36} /><span className="font-display text-2xl">Stylisme</span></Link><Link to="/auth" className="rounded-full bg-foreground px-5 py-2.5 text-sm text-primary-foreground">Entrar</Link></nav><header className="mx-auto max-w-2xl py-16 text-center"><Crown className="mx-auto text-gold" size={38} /><h1 className="mt-4 font-display text-5xl">Escolha seu plano</h1><p className="mt-4 text-muted-foreground">Comece gratuitamente. Assine quando quiser mais combinações, planejamento e informações sobre o seu armário.</p></header><div className="grid gap-4 md:grid-cols-2"><Plan title="Free" price="R$ 0" items={free} /><Plan title="Premium" price="R$ 24,90/mês" items={premium} highlighted /></div><div className="py-12 text-center"><Link to="/auth" className="inline-flex items-center gap-2 rounded-full bg-foreground px-7 py-3.5 text-sm text-primary-foreground">Começar agora <ArrowRight size={16} /></Link><p className="mt-3 text-xs text-muted-foreground">Cancele quando quiser. Pagamento seguro.</p></div></div></main>; }
function Plan({ title, price, items, highlighted }: { title: string; price: string; items: string[]; highlighted?: boolean }) { return <section className={`border p-6 ${highlighted ? "border-gold bg-card shadow-lift" : "border-border"}`}><p className="text-xs uppercase tracking-[0.22em] text-muted-foreground">{title}</p><h2 className="mt-2 font-display text-4xl">{price}</h2><ul className="mt-6 space-y-3">{items.map((item) => <li key={item} className="flex items-center gap-2 text-sm"><Check size={15} className="text-gold" />{item}</li>)}</ul></section>; }