/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppSubscriptionRouteImport } from './routes/app.subscription'
import { Route as AppStatsRouteImport } from './routes/app.stats'
import { Route as AppSettingsRouteImport } from './routes/app.settings'
import { Route as AppProfileRouteImport } from './routes/app.profile'
import { Route as AppPremiumRouteImport } from './routes/app.premium'
import { Route as AppLooksRouteImport } from './routes/app.looks'
import { Route as AppFavoritesRouteImport } from './routes/app.favorites'
import { Route as AppAiRouteImport } from './routes/app.ai'

const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppSubscriptionRoute = AppSubscriptionRouteImport.update({
  id: '/subscription',
  path: '/subscription',
  getParentRoute: () => AppRoute,
} as any)
const AppStatsRoute = AppStatsRouteImport.update({
  id: '/stats',
  path: '/stats',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppPremiumRoute = AppPremiumRouteImport.update({
  id: '/premium',
  path: '/premium',
  getParentRoute: () => AppRoute,
} as any)
const AppLooksRoute = AppLooksRouteImport.update({
  id: '/looks',
  path: '/looks',
  getParentRoute: () => AppRoute,
} as any)
const AppFavoritesRoute = AppFavoritesRouteImport.update({
  id: '/favorites',
  path: '/favorites',
  getParentRoute: () => AppRoute,
} as any)
const AppAiRoute = AppAiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/app/ai': typeof AppAiRoute
  '/app/favorites': typeof AppFavoritesRoute
  '/app/looks': typeof AppLooksRoute
  '/app/premium': typeof AppPremiumRoute
  '/app/profile': typeof AppProfileRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/stats': typeof AppStatsRoute
  '/app/subscription': typeof AppSubscriptionRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app/ai': typeof AppAiRoute
  '/app/favorites': typeof AppFavoritesRoute
  '/app/looks': typeof AppLooksRoute
  '/app/premium': typeof AppPremiumRoute
  '/app/profile': typeof AppProfileRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/stats': typeof AppStatsRoute
  '/app/subscription': typeof AppSubscriptionRoute
  '/app': typeof AppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/app/ai': typeof AppAiRoute
  '/app/favorites': typeof AppFavoritesRoute
  '/app/looks': typeof AppLooksRoute
  '/app/premium': typeof AppPremiumRoute
  '/app/profile': typeof AppProfileRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/stats': typeof AppStatsRoute
  '/app/subscription': typeof AppSubscriptionRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/app/ai'
    | '/app/favorites'
    | '/app/looks'
    | '/app/premium'
    | '/app/profile'
    | '/app/settings'
    | '/app/stats'
    | '/app/subscription'
    | '/app/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app/ai'
    | '/app/favorites'
    | '/app/looks'
    | '/app/premium'
    | '/app/profile'
    | '/app/settings'
    | '/app/stats'
    | '/app/subscription'
    | '/app'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/app/ai'
    | '/app/favorites'
    | '/app/looks'
    | '/app/premium'
    | '/app/profile'
    | '/app/settings'
    | '/app/stats'
    | '/app/subscription'
    | '/app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/subscription': {
      id: '/app/subscription'
      path: '/subscription'
      fullPath: '/app/subscription'
      preLoaderRoute: typeof AppSubscriptionRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/stats': {
      id: '/app/stats'
      path: '/stats'
      fullPath: '/app/stats'
      preLoaderRoute: typeof AppStatsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/profile': {
      id: '/app/profile'
      path: '/profile'
      fullPath: '/app/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/premium': {
      id: '/app/premium'
      path: '/premium'
      fullPath: '/app/premium'
      preLoaderRoute: typeof AppPremiumRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/looks': {
      id: '/app/looks'
      path: '/looks'
      fullPath: '/app/looks'
      preLoaderRoute: typeof AppLooksRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/favorites': {
      id: '/app/favorites'
      path: '/favorites'
      fullPath: '/app/favorites'
      preLoaderRoute: typeof AppFavoritesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/ai': {
      id: '/app/ai'
      path: '/ai'
      fullPath: '/app/ai'
      preLoaderRoute: typeof AppAiRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAiRoute: typeof AppAiRoute
  AppFavoritesRoute: typeof AppFavoritesRoute
  AppLooksRoute: typeof AppLooksRoute
  AppPremiumRoute: typeof AppPremiumRoute
  AppProfileRoute: typeof AppProfileRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppStatsRoute: typeof AppStatsRoute
  AppSubscriptionRoute: typeof AppSubscriptionRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAiRoute: AppAiRoute,
  AppFavoritesRoute: AppFavoritesRoute,
  AppLooksRoute: AppLooksRoute,
  AppPremiumRoute: AppPremiumRoute,
  AppProfileRoute: AppProfileRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppStatsRoute: AppStatsRoute,
  AppSubscriptionRoute: AppSubscriptionRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
