/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as GuiaMelhoresAppsDeGuardaRoupaRouteImport } from './routes/guia.melhores-apps-de-guarda-roupa'
import { Route as AppSubscriptionRouteImport } from './routes/app.subscription'
import { Route as AppStatsRouteImport } from './routes/app.stats'
import { Route as AppSettingsRouteImport } from './routes/app.settings'
import { Route as AppProfileRouteImport } from './routes/app.profile'
import { Route as AppPremiumRouteImport } from './routes/app.premium'
import { Route as AppPaletteRouteImport } from './routes/app.palette'
import { Route as AppLooksRouteImport } from './routes/app.looks'
import { Route as AppIdeasRouteImport } from './routes/app.ideas'
import { Route as AppHelpRouteImport } from './routes/app.help'
import { Route as AppFeedRouteImport } from './routes/app.feed'
import { Route as AppFavoritesRouteImport } from './routes/app.favorites'
import { Route as AppAiRouteImport } from './routes/app.ai'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const GuiaMelhoresAppsDeGuardaRoupaRoute =
  GuiaMelhoresAppsDeGuardaRoupaRouteImport.update({
    id: '/guia/melhores-apps-de-guarda-roupa',
    path: '/guia/melhores-apps-de-guarda-roupa',
    getParentRoute: () => rootRouteImport,
  } as any)
const AppSubscriptionRoute = AppSubscriptionRouteImport.update({
  id: '/subscription',
  path: '/subscription',
  getParentRoute: () => AppRoute,
} as any)
const AppStatsRoute = AppStatsRouteImport.update({
  id: '/stats',
  path: '/stats',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppPremiumRoute = AppPremiumRouteImport.update({
  id: '/premium',
  path: '/premium',
  getParentRoute: () => AppRoute,
} as any)
const AppPaletteRoute = AppPaletteRouteImport.update({
  id: '/palette',
  path: '/palette',
  getParentRoute: () => AppRoute,
} as any)
const AppLooksRoute = AppLooksRouteImport.update({
  id: '/looks',
  path: '/looks',
  getParentRoute: () => AppRoute,
} as any)
const AppIdeasRoute = AppIdeasRouteImport.update({
  id: '/ideas',
  path: '/ideas',
  getParentRoute: () => AppRoute,
} as any)
const AppHelpRoute = AppHelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => AppRoute,
} as any)
const AppFeedRoute = AppFeedRouteImport.update({
  id: '/feed',
  path: '/feed',
  getParentRoute: () => AppRoute,
} as any)
const AppFavoritesRoute = AppFavoritesRouteImport.update({
  id: '/favorites',
  path: '/favorites',
  getParentRoute: () => AppRoute,
} as any)
const AppAiRoute = AppAiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/app/ai': typeof AppAiRoute
  '/app/favorites': typeof AppFavoritesRoute
  '/app/feed': typeof AppFeedRoute
  '/app/help': typeof AppHelpRoute
  '/app/ideas': typeof AppIdeasRoute
  '/app/looks': typeof AppLooksRoute
  '/app/palette': typeof AppPaletteRoute
  '/app/premium': typeof AppPremiumRoute
  '/app/profile': typeof AppProfileRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/stats': typeof AppStatsRoute
  '/app/subscription': typeof AppSubscriptionRoute
  '/guia/melhores-apps-de-guarda-roupa': typeof GuiaMelhoresAppsDeGuardaRoupaRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/app/ai': typeof AppAiRoute
  '/app/favorites': typeof AppFavoritesRoute
  '/app/feed': typeof AppFeedRoute
  '/app/help': typeof AppHelpRoute
  '/app/ideas': typeof AppIdeasRoute
  '/app/looks': typeof AppLooksRoute
  '/app/palette': typeof AppPaletteRoute
  '/app/premium': typeof AppPremiumRoute
  '/app/profile': typeof AppProfileRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/stats': typeof AppStatsRoute
  '/app/subscription': typeof AppSubscriptionRoute
  '/guia/melhores-apps-de-guarda-roupa': typeof GuiaMelhoresAppsDeGuardaRoupaRoute
  '/app': typeof AppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/app/ai': typeof AppAiRoute
  '/app/favorites': typeof AppFavoritesRoute
  '/app/feed': typeof AppFeedRoute
  '/app/help': typeof AppHelpRoute
  '/app/ideas': typeof AppIdeasRoute
  '/app/looks': typeof AppLooksRoute
  '/app/palette': typeof AppPaletteRoute
  '/app/premium': typeof AppPremiumRoute
  '/app/profile': typeof AppProfileRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/stats': typeof AppStatsRoute
  '/app/subscription': typeof AppSubscriptionRoute
  '/guia/melhores-apps-de-guarda-roupa': typeof GuiaMelhoresAppsDeGuardaRoupaRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/auth'
    | '/sitemap.xml'
    | '/app/ai'
    | '/app/favorites'
    | '/app/feed'
    | '/app/help'
    | '/app/ideas'
    | '/app/looks'
    | '/app/palette'
    | '/app/premium'
    | '/app/profile'
    | '/app/settings'
    | '/app/stats'
    | '/app/subscription'
    | '/guia/melhores-apps-de-guarda-roupa'
    | '/app/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/sitemap.xml'
    | '/app/ai'
    | '/app/favorites'
    | '/app/feed'
    | '/app/help'
    | '/app/ideas'
    | '/app/looks'
    | '/app/palette'
    | '/app/premium'
    | '/app/profile'
    | '/app/settings'
    | '/app/stats'
    | '/app/subscription'
    | '/guia/melhores-apps-de-guarda-roupa'
    | '/app'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/auth'
    | '/sitemap.xml'
    | '/app/ai'
    | '/app/favorites'
    | '/app/feed'
    | '/app/help'
    | '/app/ideas'
    | '/app/looks'
    | '/app/palette'
    | '/app/premium'
    | '/app/profile'
    | '/app/settings'
    | '/app/stats'
    | '/app/subscription'
    | '/guia/melhores-apps-de-guarda-roupa'
    | '/app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  GuiaMelhoresAppsDeGuardaRoupaRoute: typeof GuiaMelhoresAppsDeGuardaRoupaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/guia/melhores-apps-de-guarda-roupa': {
      id: '/guia/melhores-apps-de-guarda-roupa'
      path: '/guia/melhores-apps-de-guarda-roupa'
      fullPath: '/guia/melhores-apps-de-guarda-roupa'
      preLoaderRoute: typeof GuiaMelhoresAppsDeGuardaRoupaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/subscription': {
      id: '/app/subscription'
      path: '/subscription'
      fullPath: '/app/subscription'
      preLoaderRoute: typeof AppSubscriptionRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/stats': {
      id: '/app/stats'
      path: '/stats'
      fullPath: '/app/stats'
      preLoaderRoute: typeof AppStatsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/profile': {
      id: '/app/profile'
      path: '/profile'
      fullPath: '/app/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/premium': {
      id: '/app/premium'
      path: '/premium'
      fullPath: '/app/premium'
      preLoaderRoute: typeof AppPremiumRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/palette': {
      id: '/app/palette'
      path: '/palette'
      fullPath: '/app/palette'
      preLoaderRoute: typeof AppPaletteRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/looks': {
      id: '/app/looks'
      path: '/looks'
      fullPath: '/app/looks'
      preLoaderRoute: typeof AppLooksRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/ideas': {
      id: '/app/ideas'
      path: '/ideas'
      fullPath: '/app/ideas'
      preLoaderRoute: typeof AppIdeasRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/help': {
      id: '/app/help'
      path: '/help'
      fullPath: '/app/help'
      preLoaderRoute: typeof AppHelpRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/feed': {
      id: '/app/feed'
      path: '/feed'
      fullPath: '/app/feed'
      preLoaderRoute: typeof AppFeedRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/favorites': {
      id: '/app/favorites'
      path: '/favorites'
      fullPath: '/app/favorites'
      preLoaderRoute: typeof AppFavoritesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/ai': {
      id: '/app/ai'
      path: '/ai'
      fullPath: '/app/ai'
      preLoaderRoute: typeof AppAiRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAiRoute: typeof AppAiRoute
  AppFavoritesRoute: typeof AppFavoritesRoute
  AppFeedRoute: typeof AppFeedRoute
  AppHelpRoute: typeof AppHelpRoute
  AppIdeasRoute: typeof AppIdeasRoute
  AppLooksRoute: typeof AppLooksRoute
  AppPaletteRoute: typeof AppPaletteRoute
  AppPremiumRoute: typeof AppPremiumRoute
  AppProfileRoute: typeof AppProfileRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppStatsRoute: typeof AppStatsRoute
  AppSubscriptionRoute: typeof AppSubscriptionRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAiRoute: AppAiRoute,
  AppFavoritesRoute: AppFavoritesRoute,
  AppFeedRoute: AppFeedRoute,
  AppHelpRoute: AppHelpRoute,
  AppIdeasRoute: AppIdeasRoute,
  AppLooksRoute: AppLooksRoute,
  AppPaletteRoute: AppPaletteRoute,
  AppPremiumRoute: AppPremiumRoute,
  AppProfileRoute: AppProfileRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppStatsRoute: AppStatsRoute,
  AppSubscriptionRoute: AppSubscriptionRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  GuiaMelhoresAppsDeGuardaRoupaRoute: GuiaMelhoresAppsDeGuardaRoupaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
